### ISSUE TITLE
Ditch composer.lock

### ISSUE THREAD

**Issue by chasegiunta** [simplygoodwork/start#25]
Any reason why this needs to be in? With a fresh install it leaves with outdated Craft install & outdated plugins (which I only noticed because a critical bug in supertable was fixed in an update).

**Comment by chrisrowe** [comment]
Not in start no but we’ll want it in the projects

**Comment by geenious** [comment]
If you're in a project with a `composer.lock` file, and you run `composer update`. Would that update the Craft version/release?

**Comment by chasegiunta** [comment]
@geenious Yep. Up to the specified version in composer.json . But I would rather run `composer install` myself or have our fancy script do it post clone.
