### ISSUE TITLE
Tailwind plugins

### ISSUE THREAD

**Issue by chrisrowe** [simplygoodwork/start#4]
And their configs

**Comment by chasegiunta** [comment]
Nice thing about these is we can at least comment out what we don't need on a project, but still have the build time/module installing issue on deployment.

- https://github.com/webdna/tailwindcss-aspect-ratio
- https://github.com/bradlc/tailwindcss-alpha
- https://github.com/webdna/tailwindcss-transition (though https://github.com/benface/tailwindcss-transitions also looks promising - haven't used it)

**Comment by chrisrowe** [comment]
Yah, I mean with Purge why not throw everything at the wall

- https://github.com/035media/tailwindcss-flexbox-order
- https://github.com/aniftyco/tailwindcss-spinner
- https://github.com/chrisrowe/tailwindcss-triangle-after
- https://github.com/chrisrowe/tailwindcss-grid

Those last 2 are particularly good 😉

**Comment by chrisrowe** [comment]
- https://github.com/chasegiunta/tailwindcss-important

**Comment by chrisrowe** [comment]
Having used https://github.com/webdna/tailwindcss-transition quite a bit I hit some annoyances about transition all, and the lack of customization. Rolling with https://github.com/benface/tailwindcss-transitions instead.

**Comment by chasegiunta** [comment]
@chrisrowe do you have to define every transition property explicitly with that, or is there some way to do a shorthand like with the old version, eg. `transition-fast` ==> `transition: all 200ms;` ?

**Comment by chrisrowe** [comment]
You could just do add an `all` key and val to the properties option to get that for sure

**Comment by chrisrowe** [comment]
https://github.com/simplygoodwork/start/commit/849897f7e46ac181db98f04be424baf8ae3bba65
